# Generated by Django 5.2.4 on 2025-07-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_prediction_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wallet',
            field=models.CharField(default='', max_length=200),
        ),
    ]
