# Generated by Django 5.2.4 on 2025-07-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_userprofile_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referal_earning',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
