# Generated by Django 5.2.4 on 2025-07-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_reference_deposit_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='investment',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
    ]
