# Generated by Django 5.2.4 on 2025-07-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_userprofile_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
    ]
