# Generated by Django 5.2.4 on 2025-07-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_userprofile_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='interest',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
