# Generated by Django 5.2.4 on 2025-07-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_userprofile_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_interest_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
