# Generated by Django 5.2.4 on 2025-07-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_userprofile_last_interest_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='investment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
