# Generated by Django 5.2.4 on 2025-09-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_userprofile_interest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='wallet',
            new_name='reference',
        ),
    ]
