# Generated by Django 5.2.4 on 2025-09-15 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_wallet_deposit_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='wallet',
        ),
    ]
